### ISSUE TITLE
User doc references not implemented command

### ISSUE THREAD

**Issue by palonsoro** [openshift/network-tools#44]
[User documentation](https://github.com/openshift/network-tools/blob/master/docs/user.md) references an hypothetical `oc adm network-tools` command that will never be implemented as per [rejected pull request](https://github.com/openshift/oc/pull/709).

So that reference should be removed and replaced by something more correct.

**Comment by palonsoro** [comment]
[Contributor documentation](https://github.com/openshift/network-tools/blob/master/docs/contributor.md) also references this and is also wrong.

**Comment by tssurya** [comment]
Thanks for opening this issue. This is totally true. Let me replace the documentation and update the new way of running the scripts.

**Comment by tssurya** [comment]
https://github.com/openshift/network-tools/pull/47 should fix this.
